#!/bin/bash

#  Copyright (C) 2015-2016 Bob Mottram
#  bob@libreserver.org
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

MIN_DIPPED_DENSITY=0.38
MIN_INTERMEDIATE=5
MAX_INTERMEDIATE=30
MAX_DIPPED_PERCENT=20
DIP_RADIUS_PERCENT=2
PEAK_THRESHOLD=0.6
MAX_VACANCY_DENSITY=0.008
MIN_DATA_SAMPLES=1000
DIP_THRESHOLD=0.2

SCAN_COMMAND="../waspscan --peak $PEAK_THRESHOLD --diprad $DIP_RADIUS_PERCENT --maxd $MAX_DIPPED_PERCENT --mindd $MIN_DIPPED_DENSITY --maxint $MAX_INTERMEDIATE --minint $MIN_INTERMEDIATE --min 0.8 --max 4.2 --minsamples $MIN_DATA_SAMPLES --maxvac $MAX_VACANCY_DENSITY --dip $DIP_THRESHOLD -f"

score=0

function scan_unknown {
    ctr_detected=0
    ctr_positive=0
    fails=0
    tollerance=0.01

    FILES=unknown/*
    for f in $FILES
    do
        echo "Scanning $f"

        ref=$(echo "$f" | awk -F '_' '{print $2}' | awk -F '.tbl' '{print $1}')

        was_detected=0
	echo "${SCAN_COMMAND} $f"
        result=$(${SCAN_COMMAND} "$f")
        if [[ $result == *"orbital_period"* ]]; then
            detected_period=$(echo $result | awk -F 'orbital_period_days ' '{print $2}')
            echo "detected period: $detected_period"	    
            score=$((score + 1))
        fi
    done
}

scan_unknown

rm *.png *.tbl *.txt

echo "$score,$PEAK_THRESHOLD,$MIN_DIPPED_DENSITY,$MIN_INTERMEDIATE,$MAX_INTERMEDIATE,$MAX_DIPPED_PERCENT,$DIP_RADIUS_PERCENT" >> results.csv

cat results.csv

exit 0
